theme = "everblush"

[editor]
line-number = "relative"
color-modes = true
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.backspace]
s = ":w"
f = ":format"
c = ":config-open"
q = ":bc"
