[[language]]
name = "odin"
auto-format = true
injection-regex = "odin"
formatter = { command = "odinfmt", args = [ "-stdin", "true" ] }

[[language]]
name = "ocaml"
formatter = { command = "ocamlformat", args = [
  "-",
  "--impl",
  # "--enable-outside-detected-project", # Enable only if you want to format files outside of projects
]}

[[language]]
name = "go"
auto-format = true
# language-servers = ["gopls", "golangci-lint2-langserver"]
language-servers = ["gopls"]
formatter = { command = "goimports" }

# [language-server.golangci-lint2-langserver]
# command = "golangci-lint-langserver"

# [language-server.golangci-lint2-langserver.config]
# command = [
#   "golangci-lint",
#   "run",
#   "--output.json.path",
#   "stdout",
#   "--show-stats=false",
#   "--issues-exit-code=1",
# ]
