inherits = "everblush"

"comment" = { fg = "magenta-light", modifiers = ["italic"] }
"keyword" = { fg = "blue", modifiers = ["italic"] }
"markup.link.text" = { fg = "cyan-light" }
"markup.link.url" = { fg = "green", modifiers = ["italic"] }
